package edu.hm.ccwi.matilda.base.model.enumeration;

import java.util.HashMap;
import java.util.Map;

public enum LibCategory {

	ACTOR_FRAMEWORKS("Actor Frameworks","Actor Frameworks",true),
	ANDROID_DB("Android DB","Database",true),
	ANDROID_PACKAGES("Android Packages","Android Packages",true),
	ANDROID_PLATFORM("Android Platform","Android Platform",true),
	ANNOTATION_PROCESSING_TOOLS("Annotation Processing Tools","Annotation Processing",true),
	APPLICATION_METRICS("Application Metrics","Logging / Tracing / Monitoring / Administration",false),
	APPLICATION_SERVERS("Application Servers","Application-/ Web-Server",true),
	ARANGODB_CLIENTS("ArangoDB Clients","Database",true),
	ASPECT_ORIENTED("Aspect Oriented","Aspect Oriented",true),
	ASSERTION_LIBRARIES("Assertion Libraries","Testing / Mocking / Evaluating",false),
	BARCODE_LIBRARIES("Barcode Libraries","Barcode Handler",true),
	BASE64_LIBRARIES("Base64 Libraries","Utilities",false),
	BENCHMARK("Benchmark","Benchmarks",false),
	BITCOIN("Bitcoin","Bitcoin",true),
	BITCOIN_LIBRARIES("Bitcoin Libraries","Bitcoin",true),
	BLOOM_FILTER_LIBRARIES("Bloom Filter Libraries", "Utilities", false),
	BPM_ENGINES("BPM Engines","Operations management",true),
	BUILD_MODELS("Build Models","Build / Deployment",false),
	BUILD_TOOLS("Build Tools","Build / Deployment",false),
	BYTECODE_LIBRARIES("Bytecode Libraries","Bytecode Libraries",true),
	CACHE_CLIENTS("Cache Clients","Caching",true),
	CACHE_IMPLEMENTATIONS("Cache Implementations","Caching",true),
	CASSANDRA_CLIENTS("Cassandra Clients","Database",true),
	CASSANDRA_DRIVERS("Cassandra Drivers", "Database", true),
	CASSANDRA_OBJECT_MAPPING("Cassandra Object Mapping", "Database", true),
	CHART_LIBRARIES("Chart Libraries","Chart Libraries",true),
	CLASSPATH_TOOLS("Classpath Tools","Classpath Tools",true),
	CLOUD_BLOB_STORAGE("Cloud Blob Storage", "Database", true),
	CLOUD_COMPUTING("Cloud Computing","Cloud Computing",true),
	CLOUD_DNS("Cloud DNS", "DNS Libraries", true),
	CLUSTER_MANAGEMENT("Cluster Management","Cluster Management",true),
	CLUSTER_MANAGMENT("Cluster Managment", "Cluster Management", true),
	CODE_ANALYZERS("Code Analyzers","Code Analyses / Dynamic Program Analyses",false),
	CODE_COVERAGE_TOOLS("Code Coverage Tools","Testing / Mocking / Evaluating",false),
	COLLECTIONS("Collections","Utilities",false),
	COLUMN_DATABASE_CLIENTS("Column Database Clients","Database",true),
	COMMAND_LINE_PARSERS("Command Line Parsers","Command Line Parsers",true),
	COMPRESSION_LIBRARIES("Compression Libraries","Compression Libraries",true),
	CONCURRENCY_LIBRARIES("Concurrency Libraries","Concurrency Libraries",true),
	CONFIGURATION_LIBRARIES("Configuration Libraries","Configuration Libraries",true),
	CONSOLE_UTILITIES("Console Utilities","Utilities",false),
	CONTENT_MANAGEMENT_SOLUTIONS("Content Management Solutions","Content Management Solutions",true),
	CORE_UTILITIES("Core Utilities","Utilities",false),
	CRAWLER("Crawler","Crawler",true),
	CSS_LESS_SASS("CSS, LESS, SASS","UI",true),
	CSV_LIBRARIES("CSV Libraries","File Handler",true),
	CUSTOMER_RELATIONSHIP_MANAGEMENT("Customer Relationship Management","Customer Relationship Management",true),
	DATABASE("Database","Database",true),
	DATE_AND_TIME_UTILITIES("Date and Time Utilities","Utilities",false),
	DB_MIGRATION_TOOLS("DB Migration Tools","Database",true),
	DEFECT_DETECTION_METADATA("Defect Detection Metadata","Code Analyses / Dynamic Program Analyses",false),
	DEPENDENCY_INJECTION("Dependency Injection","Dependency Injection",true),
	DIFF_AND_PATCH_LIBRARIES("Diff and Patch Libraries","Utilities",false),
	DIGITAL_SIGNAL_PROCESSING("Digital Signal Processing","Digital Signal Processing",true),
	DISTRIBUTED_COMMUNICATION("Distributed Communication","Distributed Communication",true),
	DISTRIBUTED_COMPUTING("Distributed Computing","Distributed Computing",true),
	DISTRIBUTED_COORDINATION("Distributed Coordination","Distributed Coordination",true),
	DISTRIBUTED_FILE_SYSTEMS("Distributed File Systems","File System",true),
	DISTRIBUTED_LOGGING("Distributed Logging", "Logging / Tracing / Monitoring / Administration", false),
	DISTRIBUTED_TRACING("Distributed Tracing","Logging / Tracing / Monitoring / Administration",false),
	DNS_LIBRARIES("DNS Libraries","DNS Libraries",true),
	DOCKER_CLIENTS("Docker Clients","Containerization",true),
	DYNAMODB_CLIENTS("DynamoDB Clients","Database",true),
	ECLIPSE_PLUGINS("Eclipse Plugins","IDE Modules",true),
	ECLIPSE_RUNTIME("Eclipse Runtime","IDE Modules",true),
	ELASTICSEARCH_CLIENTS("ElasticSearch Clients","Database",true),
	ELASTICSEARCH_DISCOVERY("ElasticSearch Discovery","Database",true),
	EMBEDDED_DATABASES("Embedded Databases","Database",true),
	EMBEDDED_SQL_DATABASES("Embedded SQL Databases","Database",true),
	ENCRYPTION_LIBRARIES("Encryption Libraries","Security / Cryptography / Authentication",true),
	ENTERPRISE_INTEGRATION("Enterprise Integration","Messaging / Integration",true),
	ENTERPRISE_SERVICE_BUS("Enterprise Service Bus","Messaging / Integration",true),
	ERLANG_INTEGRATION("Erlang Integration", "Languages / Compiler / Interpretation", true),
	ETCD_CLIENTS("Etcd Clients", "Database", true),
	EXAMPLE("Example","Example / Documentation",false),
	EXCEL_LIBRARIES("Excel Libraries","File Handler",true),
	EXCEPTION_HANDLING("Exception Handling","Exception Handling",false),
	EXPRESSION_LANGUAGES("Expression Languages","Languages / Compiler / Interpretation",true),
	EXTERNAL_PROCESS_EXECUTION("External Process Execution","External Process Execution",true),
	EXTERNAL_SORTING("External Sorting","File Handler", true),
	FILE_WATCHING_LIBRARIES("File-Watching Libraries", "File Handler", true),
	FTP_CLIENTS_AND_SERVERS("FTP Clients and Servers","Application Layer Protocol Integration",true),
	FULL_TEXT_INDEXING_LIBRARIES("Full-Text Indexing Libraries","Search Engines",true),
	FUNCTIONAL_PROGRAMMING("Functional Programming","Languages / Compiler / Interpretation",true),
	GENETIC_ALGORITHMS("Genetic Algorithms", "Genetic Algorithms", true),
	GEOSPATIAL_LIBRARIES("Geospatial Libraries","Geospatial Libraries",true),
	GEOMETRY_LIBRARIES("Geometry Libraries","Geometry Libraries",true),
	GRAPHQL_LIBRARIES("GraphQL Libraries", "Application Layer Protocol Integration", true),
	GIT_TOOLS("Git Tools","Version-control system tools",true),
	GITHUB_API("GitHub API", "Version-control system tools", true),
	GRADLE_PLUGINS("Gradle Plugins","Build / Deployment",false),
	GRAPH_ALGORITHMS("Graph Algorithms","Graph Algorithms and Tools",true),
	GRAPH_DATABASES("Graph Databases","Database",true),
	GRAPH_QUERY_LANGUAGES("Graph Query Languages","Graph Algorithms and Tools",true),
	GRAPHVIZ_LIBRARIES("GraphViz Libraries","Graph Algorithms and Tools",true),
	GWT_WIDGETS("GWT Widgets", "UI", true),
	HADOOP_DATABASES("Hadoop Databases","Database",true),
	HADOOP_QUERY_ENGINES("Hadoop Query Engines","Database",true),
	HASHING_LIBRARIES("Hashing Libraries","Hashing",true),
	HBASE_CLIENTS("HBase Clients","Database",true),
	HTML_PARSERS("HTML Parsers","File Handler",true),
	HTTP_CLIENTS("HTTP Clients","Application Layer Protocol Integration",true),
	HTTP_PROXIES("HTTP Proxies", "Application Layer Protocol Integration", true),
	I_O_UTILITIES("I/O Utilities","Utilities",false),
	I18N_LIBRARIES("I18N Libraries","Utilities",false),
	JAVA_COMPILERS_PARSERS("Java Compilers/Parsers","Languages / Compiler / Interpretation",true),
	JAVA_SPECIFICATIONS("Java Specifications","Java Specifications",true),
	JAVASCRIPT_PROCESSORS("JavaScript Processors","Languages / Compiler / Interpretation",true),
	JDBC_EXTENSIONS("JDBC Extensions","Database",true),
	JDBC_POOLS("JDBC Pools","Database",true),
	JETTY_SESSION_MANAGERS("Jetty Session Managers", "Application-/ Web-Server", true),
	JMX_LIBRARIES("JMX Libraries","Logging / Tracing / Monitoring / Administration",false),
	JOB_SCHEDULING("Job Scheduling","Job Scheduling",true),
	JPA_IMPLEMENTATIONS("JPA Implementations","Database",true),
	JSF_LIBRARIES("JSF Libraries","UI",true),
	JSON_LIBRARIES("JSON Libraries","File Handler",true),
	JSON_RPC_LIBRARIES("JSON-RPC Libraries", "Application Layer Protocol Integration", true),
	JSP_TAG_LIBRARIES("JSP Tag Libraries","UI",true),
	JVM_LANGUAGES("JVM Languages","Languages / Compiler / Interpretation",true),
	JWT_LIBRARIES("JWT Libraries","Security / Cryptography / Authentication",true),
	LANGUAGE_RUNTIME("Language Runtime","Languages / Compiler / Interpretation",true),
	LEVELDB_INTEGRATION("LevelDB Integration","Database",true),
	LOAD_TESTING("Load Testing", "Testing / Mocking / Evaluating", true),
	LOGGING_BRIDGES("Logging Bridges","Logging / Tracing / Monitoring / Administration",false),
	LOGGING_FRAMEWORKS("Logging Frameworks","Logging / Tracing / Monitoring / Administration",false),
	MACHINE_LEARNING("Machine Learning","Artificial Intelligence",true),
	MAIL_CLIENTS("Mail Clients","Mailing",true),
	MAIL_SERVER("Mail Server","Mailing",true),
	MARKDOWN_PROCESSORS("Markdown Processors","File Handler",true),
	MATH_LIBRARIES("Math Libraries","Utilities",false),
	MAVEN_ARCHETYPES("Maven Archetypes","Build / Deployment",false),
	MAVEN_PLUGINS("Maven Plugins","Build / Deployment",false),
	MAVEN_REPOSITORIES_API("Maven Repositories API","Build / Deployment",false),
	MESSAGE_BROKERS("Message Brokers","Messaging / Integration",true),
	MESSAGE_QUEUE_CLIENTS("Message Queue Clients","Messaging / Integration",true),
	MICROBENCHMARKS("Microbenchmarks","Benchmarks",false),
	MIME_TYPES_LIBRARIES("MIME Types Libraries","Utilities",false),
	MOCKING("Mocking","Testing / Mocking / Evaluating",false),
	MONEY_LIBRARIES("Money Libraries","Money Libraries",true),
	MONGODB_CLIENTS("MongoDB Clients","Database",true),
	MONGODB_OBJECT_MAPPING("MongoDB Object Mapping", "Database", true),
	MONITORING_TOOLS("Monitoring Tools","Logging / Tracing / Monitoring / Administration",false),
	MYSQL_DRIVERS("MySQL Drivers","Database",true),
	NATIVE_ACCESS_TOOLS("Native Access Tools","Native Access Tools",true),
	NATURAL_LANGUAGE_PROCESSING("Natural Language Processing","Artificial Intelligence",true),
	NETBEANS_MODULES("NetBeans Modules","IDE Modules",true),
	NETWORK_APP_FRAMEWORKS("Network App Frameworks","Application-/ Web-Server",true),
	NOSQL_DATABASES("NoSQL Databases","Database",true),
	OAUTH_LIBRARIES("OAuth Libraries","Security / Cryptography / Authentication",true),
	OAUTH_SERVERS("OAuth Servers", "Security / Cryptography / Authentication",true),
	OBJECT_POOLS("Object Pools","Utilities",false),
	OBJECT_RELATIONAL_MAPPING("Object/Relational Mapping","Database",true),
	OBJECT_SERIALIZATION("Object Serialization","Marshalling / Unmarshalling",true),
	OBJECT_SIZE_ESTIMATION("Object Size Estimation","Logging / Tracing / Monitoring / Administration",false),
	OFF_HEAP_LIBRARIES("Off-Heap Libraries","Off-Heap Libraries",true),
	OPENID_LIBRARIES("OpenID Libraries", "Security / Cryptography / Authentication", true),
	ORIENTDB_CLIENTS("OrientDB Clients","Database",true),
	OSGI_CONTAINERS("OSGI Containers","OSGi",true),
	OSGI_FRAMEWORKS("OSGI Frameworks","OSGi",true),
	OSGI_UTILITIES("OSGI Utilities","OSGi",true),
	PARSER_GENERATORS("Parser Generators","Languages / Compiler / Interpretation",true),
	PDF_LIBRARIES("PDF Libraries","File Handler",true),
	PHYSICS("Physics","Physics",true),
	PHYSICS_ENGINES("Physics Engines","Physics",true),
	POSTGRESQL_DRIVERS("PostgreSQL Drivers","Database",true),
	PROGRAMMABLE_LOGIC_CONTROLLER("Programmable Logic Controller","Programmable Logic Controller",true),
	PYTHON_INTEGRATION("Python Integration","Languages / Compiler / Interpretation",true),
	RDF_LIBRARIES("RDF Libraries","Database",true),
	REDIS_CLIENTS("Redis Clients","Database",true),
	REFLECTION_LIBRARIES("Reflection Libraries","Reflection Libraries",true),
	REGULAR_EXPRESSION_LIBRARIES("Regular Expression Libraries","Utilities",false),
	REST_FRAMEWORK("REST Framework","Application Layer Protocol Integration",true),
	RETHINKDB_CLIENTS("RethinkDB Clients", "Database", true),
	RSS_AND_ATOM_LIBRARIES("RSS and Atom Libraries", "RSS and Atom Libraries", true),
	RULE_ENGINES("Rule Engines","Rule Engines",true),
	S3_CLIENTS("S3 Clients","File System",true),
	SCALA_COMPILERS("Scala Compilers","Languages / Compiler / Interpretation",true),
	SEARCH_ENGINES("Search Engines","Search Engines",true),
	SECURITY_FRAMEWORKS("Security Frameworks","Security / Cryptography / Authentication",true),
	SIMPLE_NETWORK_MANAGEMENT_PROTOCOL("Simple Network Management Protocol","Application Layer Protocol Integration",true),
	SMPP_LIBRARIES("SMPP Libraries","Application Layer Protocol Integration",true),
	SMS_LIBRARY("Sms Library","Communication Protocol Integration",true),
	SOCIAL_NETWORK_CLIENTS("Social Network Clients","Social Network Clients",true),
	SOFTWARE_TRANSACTIONAL_MEMORY("Software Transactional Memory", "Concurrency Libraries", true),
	SONAR_PLUGINS("Sonar Plugins", "Code Analyses / Dynamic Program Analyses", false),
	SOURCE_CODE_MANAGEMENT("Source Code Management", "Version-control system tools",true),
	SQL_DRIVERS("SQL Drivers","Database",true),
	SSH_LIBRARIES("SSH Libraries","Application Layer Protocol Integration",true),
	SSL_COMPONENT_LIBRARIES("SSL Component Libraries","Application Layer Protocol Integration",true),
	STREAM_PROCESSING("Stream Processing","Messaging / Integration",true),
	STRING_UTILITIES("String Utilities","Utilities",false),
	SUBVERSION_TOOLS("Subversion Tools","Version-control system tools",true),
	SVG_LIBRARIES("SVG Libraries","File Handler",true),
	SWING_LAYOUTS("Swing Layouts","UI",true),
	SWING_LIBRARIES("Swing Libraries","UI",true),
	SWING_UI_TESTING("Swing UI Testing", "Testing / Mocking / Evaluating",false),
	TEMPLATE_ENGINES("Template Engines","Template Engines / Schema Provider",true),
	TESTING_FRAMEWORKS("Testing Frameworks","Testing / Mocking / Evaluating",false),
	TIMESERIES_LIBRARIES("Timeseries Libraries","Timeseries Libraries",true),
	TOMCAT_SESSION_MANAGERS("Tomcat Session Managers","Application-/ Web-Server",true),
	TRANSACTION_APIS_MANAGERS("Transaction APIs/Managers","Distributed Communication",true),
	UML_MODELING("UML Modeling","Graph Algorithms and Tools",true),
	UNITS_OF_MEASUREMENT("Units of Measurement","Utilities",false),
	URI_LIBRARIES("URI Libraries", "Utilities", false),
	UUID_GENERATORS("UUID Generators","Utilities",false),
	VALIDATION_FRAMEWORKS("Validation Frameworks","Utilities",false),
	VECTOR_MATRIX_LIBRARIES("Vector/Matrix Libraries","Utilities",false),
	VIRTUAL_FILE_SYSTEMS("Virtual File Systems","File System",true),
	WEB_APPLICATIONS("Web Applications","Web Applications",true),
	WEB_ASSETS("Web Assets","UI",true),
	WEB_BROWSER_AUTOMATION("Web Browser Automation","Testing / Mocking / Evaluating",false),
	WEB_CRAWLERS("Web Crawlers","Crawler",true),
	WEB_FRAMEWORKS("Web Frameworks","UI",true),
	WEB_SERVERS("Web Servers","Application-/ Web-Server",true),
	WEB_TESTING("Web Testing","Testing / Mocking / Evaluating",false),
	WEB_UPLOAD_MANAGERS("Web Upload Managers","Web Applications",true),
	WEBSERVICES_METADATA("WebServices Metadata","Application Layer Protocol Integration",true),
	WEBSOCKET_CLIENTS("WebSocket Clients","Application Layer Protocol Integration",true),
	WORKFLOW_MANAGER("Workflow Manager","Workflow Manager",true),
	XML_PROCESSING("XML Processing","File Handler",true),
	XMPP_INTEGRATION_LIBRARIES("XMPP Integration Libraries","Communication Protocol Integration",true),
	XPATH_LIBRARIES("XPath Libraries","File Handler",true),
	YAML_PARSERS("YAML Parsers","File Handler",true),

	// ADDITIONAL CATEGORIES DUE TO WRONG MAPPINGS IN EARLIER CRAWLING-ATTEMPTS -> WRONG CATEGORIES ALREADY IN DB
	CODE_ANALYSES("Code Analyses", "Code Analyses / Dynamic Program Analyses", false),
	MANAGING_MONITORING("Managing / Monitoring", "Logging / Tracing / Monitoring / Administration", false),
	SECURITY_CRYPTOGRAPHY_AUTHENTIFICATION("Security Cryptography Authentification", "Security / Cryptography / Authentication", true);

	// Reverse-lookup map for getting a LibCategory-Object for a matildaCategory
	private static final Map<String, LibCategory> matildaCategoryLookup = new HashMap<>();

	static {
		for (LibCategory libCategory : LibCategory.values()) {
			matildaCategoryLookup.put(libCategory.getMatildaCategory(), libCategory);
		}
	}

	/**
	 * Retrieve Matilda-category from String representation
	 *
	 * @return The libCategory by the matildaCategory-String or null, if String is unknown.
	 */
	public static LibCategory getByMatildaCategory(String matildaCategory) {
		return matildaCategoryLookup.get(matildaCategory);
	}

	private final String name;
	private final String matildaCategory;
	private final boolean relevant;

	LibCategory(String name, String matildaCategory, boolean relevant) {
		this.name = name;
		this.matildaCategory = matildaCategory;
		this.relevant = relevant;
	}

	public String getName() {
		return name;
	}

	public String getMatildaCategory() {
		return matildaCategory;
	}
	
	public boolean isRelevant() {
		return relevant;
	}
}